# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

jobs:
  "php81":
    docker:
      - image: aimeos/ci-php:8.1
    steps:
      - run: sudo apt-get update && sudo apt-get install -y beanstalkd rabbitmq-server
      - checkout
      - run: git clone --depth=50 --branch=2024.10 https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-mqueue && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php81-{{ checksum "composer.json" }}
      - run: composer req --no-update "php-amqplib/php-amqplib:~2.0" "pda/pheanstalk:~3.0" "stomp-php/stomp-php:~3.0"
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php81-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-mqueue testext

  "php82":
    docker:
      - image: aimeos/ci-php:8.2
    steps:
      - run: sudo apt-get update && sudo apt-get install -y beanstalkd rabbitmq-server
      - checkout
      - run: git clone --depth=50 --branch=2024.10 https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-mqueue && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php82-{{ checksum "composer.json" }}
      - run: composer req --no-update "php-amqplib/php-amqplib:~2.0" "pda/pheanstalk:~3.0" "stomp-php/stomp-php:~3.0"
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php82-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-mqueue coverageext
      - run: ./vendor/bin/php-coveralls --root_dir ext/ai-mqueue -o tests/coveralls.json -vvv -x tests/coverage.xml

  "php83":
    docker:
      - image: aimeos/ci-php:8.3
    steps:
      - run: sudo apt-get update && sudo apt-get install -y beanstalkd rabbitmq-server
      - checkout
      - run: git clone --depth=50 --branch=2024.10 https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-mqueue && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php83-{{ checksum "composer.json" }}
      - run: composer req --no-update "php-amqplib/php-amqplib:~2.0" "pda/pheanstalk:~3.0" "stomp-php/stomp-php:~3.0"
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php83-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-mqueue testext

  "php84":
    docker:
      - image: aimeos/ci-php:8.4
    steps:
      - run: sudo apt-get update && sudo apt-get install -y beanstalkd rabbitmq-server
      - checkout
      - run: git clone --depth=50 --branch=2024.10 https://github.com/aimeos/aimeos-core ../aimeos-core
      - run: cd .. && mv project aimeos-core/ext/ai-mqueue && mv aimeos-core project && cd project
      - restore_cache:
          keys:
            - php84-{{ checksum "composer.json" }}
      - run: composer req --no-update "php-amqplib/php-amqplib:~2.0" "pda/pheanstalk:~3.0" "stomp-php/stomp-php:~3.0"
      - run: composer update -n --prefer-dist
      - save_cache:
          key: php84-{{ checksum "composer.json" }}
          paths: [./vendor]
      - run: ./vendor/bin/phing -Ddir=ext/ai-mqueue testext

workflows:
  version: 2
  unittest:
    jobs:
      - "php81"
      - "php82"
      - "php83"
      - "php84"
